In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("players_22.csv")

# Tampilkan dimensi data dan kolom awal
print(df.shape)

# Tampilkan 5 data teratas
df.head()

(19239, 110)

C:\Users\jeezx\AppData\Local\Temp\ipykernel_27116\2763179745.py:4: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("players_22.csv")

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [54]:
# Cek tipe data dan missing value
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Columns: 110 entries, sofifa_id to nation_flag_url
dtypes: float64(16), int64(44), object(50)
memory usage: 16.1+ MB

In [55]:
# Hitung missing value setiap kolom
missing_values = df.isnull().sum()
missing_values[missing_values > 0].sort_values(ascending=False)

nation_jersey_number         18480
nation_position              18480
nation_team_id               18480
nation_logo_url              18480
club_loaned_from             18137
player_tags                  17798
goalkeeping_speed            17107
player_traits                 9841
pace                          2132
shooting                      2132
physic                        2132
defending                     2132
dribbling                     2132
passing                       2132
release_clause_eur            1176
club_joined                   1163
value_eur                       74
wage_eur                        61
club_team_id                    61
club_contract_valid_until       61
club_jersey_number              61
league_level                    61
club_position                   61
league_name                     61
club_name                       61
club_logo_url                   61
club_flag_url                   61
dtype: int64

In [56]:
# Statistik deskriptif kolom numerik
df.describe()

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,19239.000000,19239.000000,19239.000000,1.916500e+04,19178.000000,19239.000000,19239.000000,19239.000000,19178.000000,19178.000000,...,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,2132.000000
mean,231468.086959,65.772182,71.079370,2.850452e+06,9017.989363,25.210822,181.299704,74.943032,50580.498123,1.354364,...,57.929830,46.601746,48.045584,45.906700,16.406102,16.192474,16.055356,16.229274,16.491814,36.439962
std,27039.717497,6.880232,6.086213,7.613700e+06,19470.176724,4.748235,6.863179,7.069434,54401.868535,0.747865,...,12.159326,20.200807,21.232718,20.755683,17.574028,16.839528,16.564554,17.059779,17.884833,10.751563
min,41.000000,47.000000,49.000000,9.000000e+03,500.000000,16.000000,155.000000,49.000000,1.000000,1.000000,...,12.000000,4.000000,5.000000,5.000000,2.000000,2.000000,2.000000,2.000000,2.000000,15.000000
25%,214413.500000,61.000000,67.000000,4.750000e+05,1000.000000,21.000000,176.000000,70.000000,479.000000,1.000000,...,50.000000,29.000000,28.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,27.000000
50%,236543.000000,66.000000,71.000000,9.750000e+05,3000.000000,25.000000,181.000000,75.000000,1938.000000,1.000000,...,59.000000,52.000000,56.000000,53.000000,11.000000,11.000000,11.000000,11.000000,11.000000,36.000000
75%,253532.500000,70.000000,75.000000,2.000000e+06,8000.000000,29.000000,186.000000,80.000000,111139.000000,1.000000,...,66.000000,63.000000,65.000000,63.000000,14.000000,14.000000,14.000000,14.000000,14.000000,45.000000
max,264640.000000,93.000000,95.000000,1.940000e+08,350000.000000,54.000000,206.000000,110.000000,115820.000000,5.000000,...,96.000000,93.000000,93.000000,92.000000,91.000000,92.000000,93.000000,92.000000,90.000000,65.000000

In [57]:
# Data Preparation

# Pilih fitur-fitur yang dianggap memengaruhi nilai pemain
selected_columns = [
    'value_eur',         # Target regresi
    'overall',
    'potential',
    'age',
    'wage_eur',
    'height_cm',
    'weight_kg',
    'player_positions',
    'skill_moves',
    'weak_foot',
    'international_reputation',
    'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic'
]

# Subset data
df_model = df[selected_columns].copy()
df_model.head()

,value_eur,overall,potential,age,wage_eur,height_cm,weight_kg,player_positions,skill_moves,weak_foot,international_reputation,pace,shooting,passing,dribbling,defending,physic
0,78000000.0,93,93,34,320000.0,170,72,"RW, ST, CF",4,4,5,85.0,92.0,91.0,95.0,34.0,65.0
1,119500000.0,92,92,32,270000.0,185,81,ST,4,4,5,78.0,92.0,79.0,86.0,44.0,82.0
2,45000000.0,91,91,36,270000.0,187,83,"ST, LW",5,4,5,87.0,94.0,80.0,88.0,34.0,75.0
3,129000000.0,91,91,29,270000.0,175,68,"LW, CAM",5,5,5,91.0,83.0,86.0,94.0,37.0,63.0
4,125500000.0,91,91,30,350000.0,181,70,"CM, CAM",4,5,4,76.0,86.0,93.0,88.0,64.0,78.0

In [58]:
# Cek missing values
df_model.isnull().sum()

value_eur                     74
overall                        0
potential                      0
age                            0
wage_eur                      61
height_cm                      0
weight_kg                      0
player_positions               0
skill_moves                    0
weak_foot                      0
international_reputation       0
pace                        2132
shooting                    2132
passing                     2132
dribbling                   2132
defending                   2132
physic                      2132
dtype: int64

In [59]:
# Hapus baris dengan missing value
df_model.dropna(inplace=True)
print("Setelah menghapus baris kosong:", df_model.shape)

Setelah menghapus baris kosong: (17041, 17)

In [60]:
from sklearn.preprocessing import LabelEncoder

# Encode kolom 'player_positions' menjadi label numerik
le = LabelEncoder()
df_model['player_positions'] = le.fit_transform(df_model['player_positions'])

In [61]:
# Cek kembali data bersih
df_model.info()
df_model.head()

<class 'pandas.core.frame.DataFrame'>
Index: 17041 entries, 0 to 19238
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   value_eur                 17041 non-null  float64
 1   overall                   17041 non-null  int64
 2   potential                 17041 non-null  int64
 3   age                       17041 non-null  int64
 4   wage_eur                  17041 non-null  float64
 5   height_cm                 17041 non-null  int64
 6   weight_kg                 17041 non-null  int64
 7   player_positions          17041 non-null  int64
 8   skill_moves               17041 non-null  int64
 9   weak_foot                 17041 non-null  int64
 10  international_reputation  17041 non-null  int64
 11  pace                      17041 non-null  float64
 12  shooting                  17041 non-null  float64
 13  passing                   17041 non-null  float64
 14  dribbling                 17041 non-null  float64
 15  defending                 17041 non-null  float64
 16  physic                    17041 non-null  float64
dtypes: float64(8), int64(9)
memory usage: 2.3 MB

,value_eur,overall,potential,age,wage_eur,height_cm,weight_kg,player_positions,skill_moves,weak_foot,international_reputation,pace,shooting,passing,dribbling,defending,physic
0,78000000.0,93,93,34,320000.0,170,72,603,4,4,5,85.0,92.0,91.0,95.0,34.0,65.0
1,119500000.0,92,92,32,270000.0,185,81,634,4,4,5,78.0,92.0,79.0,86.0,44.0,82.0
2,45000000.0,91,91,36,270000.0,187,83,657,5,4,5,87.0,94.0,80.0,88.0,34.0,75.0
3,129000000.0,91,91,29,270000.0,175,68,371,5,5,5,91.0,83.0,86.0,94.0,37.0,63.0
4,125500000.0,91,91,30,350000.0,181,70,168,4,5,4,76.0,86.0,93.0,88.0,64.0,78.0

In [62]:
# Modelling (Regresi)

# Split data untuk regresi

from sklearn.model_selection import train_test_split

# Fitur dan target
X = df_model.drop(columns=['value_eur'])
y = df_model['value_eur']

# Split train-test (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (13632, 16)
Test shape: (3409, 16)

In [63]:
# Modelling (Random Forest Regressor)

from sklearn.ensemble import RandomForestRegressor

# Inisialisasi dan latih model
rf_reg = RandomForestRegressor(
    n_estimators=200,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)
rf_reg.fit(X_train, y_train)

import joblib

# Simpan model regresi ke file
joblib.dump(rf_reg, 'rf_regression_model.pkl')

# # Load model dari file
# rf_reg_loaded = joblib.load('rf_regression_model.pkl')

['rf_regression_model.pkl']

In [64]:
# Evaluasi Model

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Prediksi
y_pred = rf_reg.predict(X_test)

# Evaluasi
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.4f}")

RMSE: 1109363.34
R² Score: 0.9825

In [66]:
# Buat kolom value class

# Buat kategori dari nilai transfer (value_eur)
bins = [0, 1_000_000, 15_000_000, df_model['value_eur'].max()]
labels = ['Low', 'Medium', 'High']

df_model['value_class'] = pd.cut(df_model['value_eur'], bins=bins, labels=labels)

In [67]:
# Split data untuk klasifikasi 

from sklearn.model_selection import train_test_split

# Fitur untuk klasifikasi (tanpa kolom 'value_eur' dan 'value_class')
X_cls = df_model.drop(columns=['value_eur', 'value_class'])
y_cls = df_model['value_class']

# Split data 80-20
Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_cls, y_cls, test_size=0.2, random_state=42, stratify=y_cls
)

In [69]:
# Modelling (Classification)

# Scaling Data
from sklearn.preprocessing import StandardScaler

# Scaling fitur
scaler = StandardScaler()
Xc_train_scaled = scaler.fit_transform(Xc_train)
Xc_test_scaled = scaler.transform(Xc_test)

In [70]:
# Training model KNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Inisialisasi dan latih model KNN
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(Xc_train_scaled, yc_train)

# Prediksi data test
yc_pred_knn = knn_model.predict(Xc_test_scaled)

In [ ]:
# Evaluasi Model

print("Classification Report (KNN):\n")
print(classification_report(yc_test, yc_pred_knn))

print("Confusion Matrix (KNN):")
print(confusion_matrix(yc_test, yc_pred_knn))

# Simpan Model
import joblib

# Simpan model KNN
joblib.dump(knn_model, "knn_classifier_model.pkl")

# Simpan scaler (karena KNN butuh data yang terstandarisasi)
joblib.dump(scaler, "scaler_knn.pkl")


# # Gunakan kembali:
# X_new_scaled = scaler_loaded.transform(X_new_data)
# prediksi = knn_loaded.predict(X_new_scaled)

Classification Report (KNN):

              precision    recall  f1-score   support

        High       0.85      0.69      0.76       132
         Low       0.92      0.91      0.92      1728
      Medium       0.88      0.90      0.89      1549

    accuracy                           0.90      3409
   macro avg       0.88      0.84      0.86      3409
weighted avg       0.90      0.90      0.90      3409

Confusion Matrix (KNN):
[[  91    0   41]
 [   0 1580  148]
 [  16  133 1400]]

['scaler_knn.pkl']

In [94]:
import tkinter as tk
from tkinter import messagebox, ttk
import joblib
import numpy as np
import pandas as pd

# Load model dan scaler
reg_model = joblib.load("rf_regression_model.pkl")
knn_model = joblib.load("knn_classifier_model.pkl")
scaler = joblib.load("scaler_knn.pkl")

# Mapping
position_mapping = {
    "ST": 0, "CF": 1, "CAM": 2, "CM": 3, "CDM": 4, "LM": 5, "RM": 6,
    "LW": 7, "RW": 8, "CB": 9, "LB": 10, "RB": 11, "LWB": 12, "RWB": 13, "GK": 14
}
skill_foot_options = [1, 2, 3, 4, 5]

# Fitur
features = ['overall', 'potential', 'age', 'wage_eur', 'height_cm',
            'weight_kg', 'player_positions', 'skill_moves', 'weak_foot', 'international_reputation',
            'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']

BG_COLOR = "#f8f9fa"
HEADER_COLOR = "#343a40"
BUTTON_COLOR = "#007bff"
TEXT_COLOR = "#212529"

# Fungsi prediksi
def predict():
    try:
        input_data = []
        for f in features:
            if f == 'player_positions':
                pos = player_pos_var.get()
                encoded = position_mapping.get(pos, 0)
                input_data.append(encoded)
            elif f == 'skill_moves':
                input_data.append(int(skill_var.get()))
            elif f == 'weak_foot':
                input_data.append(int(foot_var.get()))
            else:
                input_data.append(float(entries[f].get()))

        input_df = pd.DataFrame([input_data], columns=features)
        price_pred = reg_model.predict(input_df)[0]
        scaled = scaler.transform(input_df)
        class_pred = knn_model.predict(scaled)[0]

        messagebox.showinfo("Hasil Prediksi",
                            f"\U0001F4B6 Estimasi Nilai Transfer: €{int(price_pred):,}\n\nKategori Nilai: {class_pred}")

    except Exception as e:
        messagebox.showerror("Error", str(e))

# GUI setup
root = tk.Tk()
root.title("Prediksi Nilai Transfer Pemain Bola")
root.geometry("600x850")
root.configure(bg=BG_COLOR)

header = tk.Label(root, text="Prediksi Nilai Transfer Pemain", font=("Helvetica", 18, "bold"),
                  bg=HEADER_COLOR, fg="white", pady=15)
header.pack(fill="x")

form_frame = tk.Frame(root, bg=BG_COLOR)
form_frame.pack(pady=20)

entries = {}
player_pos_var = tk.StringVar(value="ST")
skill_var = tk.StringVar(value="3")
foot_var = tk.StringVar(value="3")

for f in features:
    frame = tk.Frame(form_frame, bg=BG_COLOR)
    frame.pack(padx=10, pady=6, fill="x")

    label = tk.Label(frame, text=f.capitalize().replace("_", " "), font=("Arial", 10), width=25, anchor="w", bg=BG_COLOR, fg=TEXT_COLOR)
    label.pack(side="left")

    if f == 'player_positions':
        dropdown = ttk.Combobox(frame, textvariable=player_pos_var, values=list(position_mapping.keys()), state="readonly")
        dropdown.pack(side="right", expand=True, fill="x")
    elif f == 'skill_moves':
        dropdown = ttk.Combobox(frame, textvariable=skill_var, values=skill_foot_options, state="readonly")
        dropdown.pack(side="right", expand=True, fill="x")
    elif f == 'weak_foot':
        dropdown = ttk.Combobox(frame, textvariable=foot_var, values=skill_foot_options, state="readonly")
        dropdown.pack(side="right", expand=True, fill="x")
    else:
        ent = tk.Entry(frame, font=("Arial", 10))
        ent.pack(side="right", expand=True, fill="x")
        entries[f] = ent

predict_btn = tk.Button(root, text="\U0001F52E Prediksi Sekarang", font=("Arial", 12, "bold"),
                        bg=BUTTON_COLOR, fg="white", padx=20, pady=10, command=predict)
predict_btn.pack(pady=20)

footer = tk.Label(root, text="Dibuat oleh Tim Machine Learning", font=("Arial", 9),
                  bg=BG_COLOR, fg="#6c757d")
footer.pack(pady=10)

root.mainloop()

In [89]:
# mapping = dict(zip(le.classes_, le.transform(le.classes_)))
# for k, v in mapping.items():
#     print(f"{k}: {v}")